sudo: false
rvm:
  - '2.2'
  - '2.1'
  - '2.0'
  - '1.9'
notifications:
  email:
    - tim@github.com

deploy:
  provider: rubygems
  api_key:
    secure: cPOwxSifAyfPVz+VP5YNuWXwIiIWfc3BHXCsbFNyieznlMFLlkYO+ENjzl+3TqaA5bXngjTbMRYlWuZyf2/Cm/0LHMQYJlaaM8OI3XSmUdKbus6lA212Gpc1lcj2wIirRs+it34TJ+UnBMsmQY6Sc66MbnWcd3fBYshjDk5LAzYQ5SS5kREBx1xkl3S8zLQP+4D+Hqsu3WBBiTQ1hAWnnyqqWvurfmt0tJDLOU99rgPPhpfQ3kwyjxersKCE+QyVG41EBbkyxsW76qJL9xu7IHTQkb6VvUKmtluKxv7EBlzjc3bUWL6GbV7pMPzJ/RtQrsYgWUP0NdxirBorBgoNRdn/goATLHhGuCvubOsU75SOyHgLPs+yqvsMA6s1o89sVxHzL9ztrmmF375B6H3NHbNKjpbh3X31EK+E72anVT3X4SuIKX/VPHYIQY3mGLrkmASQLxcbcPMhKhm01aGY9ql0SnT6KsNkvIFLLDXoHo9S/0svd6shogb2BmPl/GQT5VWBTjVsBs5vD7hIC1K5bYhVa2YeHrAsryexNqQVck00LMhZZkkpWPR0kYfpdnmrNMVQDP622nxPoXhho9y8J9mwD9b3hYohjrtWa71vulZmGAlo1+mFdCuJp0eMCAeQH9u4li2islaWVGdsl7TLiaVENw8RaDcS2pbmPLDusU0=
  on:
    tags: true
