name: Test

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  BUNDLE_WITHOUT: release

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
        puppet:
          - "8"
          - "7"
          - "6"
        exclude:
          - puppet: "8"
            ruby: "2.7"
          - puppet: "8"
            ruby: "3.0"
          - puppet: "6"
            ruby: "3.0"
          - puppet: "6"
            ruby: "3.1"
          - puppet: "6"
            ruby: "3.2"
    name: Ruby ${{ matrix.ruby }} + Puppet ${{ matrix.puppet }}
    env:
      PUPPET_VERSION: "~> ${{ matrix.puppet }}.0"
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Show Puppet version
        run: bundle exec puppet --version
      - name: Run tests
        run: bundle exec rake
      - name: Verify gem builds
        run: gem build *.gemspec
  tests:
    needs:
      - test
    runs-on: ubuntu-latest
    name: Test suite
    steps:
      - run: echo Test suite completed
